//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fiap.Exemplo02.MVC.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Projeto
    {
        public int Id { get; set; }

        [Display(Name = "Nome do projeto")]
        public string Nome { get; set; }

        [Display(Name = "Descrição do projeto")]
        public string Descricao { get; set; }

        [Display(Name = "Início do projeto")]
        public System.DateTime DataInicio { get; set; }

        [Display(Name = "Término do projeto")]
        public Nullable<System.DateTime> DataTermino { get; set; }
        public bool Entregue { get; set; }
    
        public virtual Grupo Grupo { get; set; }
    }
}
